FROM ubuntu:20.10
LABEL maintainer="Carlos Justiniano cjus@ieee.org"
EXPOSE 16000

RUN apt-get update -y && \
    apt-get install -y python python3-pip python3-dev

COPY ./requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN pip3 install -r requirements.txt
COPY . /usr/src/app
CMD tail -f /dev/null

