FROM ubuntu:16.04
LABEL maintainer="Carlos Justiniano cjus@ieee.org"
EXPOSE 15000

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev

COPY ./requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app
RUN pip3 install -r requirements.txt
COPY . /usr/src/app
CMD tail -f /dev/null

